### ISSUE TITLE
Default pre-set parameter values

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#28]
For serum escape:
times-seen at 4
functional filter at -1.5
ACE2 affinity at -1.5

For ACE2 affinity data:
Functional filter set at -1.5
times-seen at 4

I think particularly for RBD library times-seen at 4 would help (it had more variants and may be a bit more bottlenecked) for full spike 3 or 4 is fine. If for correlation plots using different times-seen options work then let's set 4 and 3 for RBD and full-spike, respectively if not then I would have 4 times-seen for both. Otherwise the other params should be common across both libraries. I think these defaults work for BA.2 library as well.

**Comment by jbloom** [comment]
This makes sense. If you think `times_seen` of 3 is OK for non-RBD, let's maybe go with that to just maximize mutations, and 4 for RBD.

Do you want me to update these or do you want to? I'm fine either way!

**Comment by jbloom** [comment]
Done for XBB.1.5 RBD repo.

**Comment by jbloom** [comment]
Done for BA.2 ACE2 affinity repo.

**Comment by jbloom** [comment]
Done for all repos in [9260df8](https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/commit/9260df8b839b61a3df26862d232aaeb91899cd7e)
