### ISSUE TITLE
color correlations RBD / non RBD

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#39]
@jbloom can we have BA.2 vs XBB.1.5 full spike ACE2 affinity plot like the first one in [here](https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_spike_DMS/htmls/affinity_corr.html) colored by RBD vs non-RBD sites? I know I can switch the view to non-RBD or RBD on those plot but the scale changes as well, and I'd prefer both both to be plotted on the same scale for figure 2.

**Comment by jbloom** [comment]
Sorry, I was going to get to this. But if you are doing it, I think it should be faceted, not colored. Coloring it honestly doesn't really help much as most of the points are on top of each other.
