### ISSUE TITLE
figure of mutation effects on cell entry by domain and mutation type

### ISSUE THREAD

**Issue by jbloom** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#45]
@Bernadetadad, here is a draft plot to show for the distribution of mutation effects for Fig 2.
<img width="564" alt="Screenshot 2023-10-02 at 8 57 41 PM" src="https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/assets/1906801/e587f677-91c9-458e-9a9c-07a56d49556c">

Does this look OK? 

It is a bit confounded because the subsets of mutations shown differ among libraries so it is not necessarily representative of tolerance to all mutations in those domains, but could still be useful to show?

Also, is the color code OK or should I change it?

**Comment by Bernadetadad** [comment]
I think it's maybe more confounded by the fact that the number of mutations per category is very different, e.g. we have very few deletions in S2 in XBB15 and most are actually in the very end of spike, so it looks like they are well tolerated - I'm a bit worried about that impression. Similarly for other domains. Do you think maybe a violin plot with actual dots for each mutation shown would be better?

**Comment by Bernadetadad** [comment]
Color scheme is fine whatever, I have some code for the paper for each domain that takes no time to change in illustrator.

**Comment by jbloom** [comment]
I can add a filter for how many times a category must be observed to show, like this:

<img width="610" alt="Screenshot 2023-10-02 at 9 23 53 PM" src="https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/assets/1906801/f2667b02-f0b1-4f0a-8cda-c9f329c08873">

But I'm not sure that is better? It is mostly driven by biases in what mutations we picked. I think the main thing this plot would show is: stop codon worse than deletion worse than substitution, and some sense of range of effects.

I played around with point plots, but they don't look good because number of mutations is so different among categories.

What do you think? I think we basically need to go with original plot (or one with n mutations in category filter in this plot) or no distribution plot.

**Comment by Bernadetadad** [comment]
Lets go with original one, it kind of works with what we want to say in the text and we can say something in the legend (I think we do in the main text already) about biased mutation picking in our libraries.

**Comment by jbloom** [comment]
@Bernadetadad, the histograms are added in this notebook: https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_spike_DMS/notebooks/func_effects_dist.html
