### ISSUE TITLE
Change from ACE2 affinity to spike ACE2 binding

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#61]
I think "binding" would be a better term to use for what our ACE2 neutralization assays are measuring as opposed to "affinity".

**Comment by jbloom** [comment]
So I will change name in pipeline from `ACE2 affinity` to `ACE2 binding`, does that seem correct?

**Comment by Bernadetadad** [comment]
yes
