### ISSUE TITLE
is ACE2 filter too stringent in `summaries_config.yml`

### ISSUE THREAD

**Issue by jbloom** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#63]
@Bernadetadad, while you are looking at data, I just wanted to flag this one.

I can't quite remember why we set the ACE2 affinity filter to -1.5 in `summaries_config.yaml` rather than something like -2. But I am sort of wondering about this, as it is filtering out sites where I think we still have good measurements. For instance, in the histograms in Figure 2 of paper we have the values clamped at +/-2, and the difference between -1.5 and -2 does seem like something we think is real. Also, I think the functional effects filter may already be effectively removing mutations with values that are unreliable.

Anyway, if there is a good reason to keep it at -1.5 we can do so, but otherwise I advocate moving it to -2. We can discuss tomorrow too if you want. 

Also, this would make 473 look like more of an escape mutation, but then we can just explain in new things we are adding to figures why that is a site with lots of escape but mostly bad for ACE2. Right now many mutations that are true escape but also are bad for affinity are being filtered at 473.

**Comment by Bernadetadad** [comment]
I'm okay with setting ACE2 filter back to -2
