### ISSUE TITLE
Group serum escape by number of previous infections

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#78]
@jbloom a reviewer asks to comment on different immunological histories. Even though sera histories are probably to heterogeneous to make any useful between-group comparisons to provide a response perhaps we could make escape plots comparing individuals with a single infection vs those with >1 previous infection. I could imagine this being a version of an overlapping summary plot we have now but faceted by the number of infections. We already have logoplots in Ext. Fig. 6 for each sera I could remake that figure and group logoplots by number of infections but that many logoplots is kind of a lot to look and compare at so maybe just a summary lineplot that will probably show that most of the key escape sites between the two groups are the same would make a point better.

**Comment by jbloom** [comment]
Sounds good, working on this now.

**Comment by jbloom** [comment]
@Bernadetadad, a plot showing what should work for this is at the bottom of this new notebook in the docs:
https://dms-vep.org/SARS-CoV-2_XBB.1.5_spike_DMS/notebooks/escape_by_prior_infections.html
