### ISSUE TITLE
Mutation fitness correlations by spike domain

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#82]
@jbloom one of the reviewers had the following comment:

_Different methods might exhibit various efficiencies for predicting mutations on different regions of the Spike. Is it possible to analyze the performance the efficiency of predicting the prevalence of mutations of each method for different regions on the Spike separately (NTD, RBD, S2 ...)_

Looks like they want some sort of mutation-level analysis here. Maybe we could have some correlation plots comparing mutation fitness from Neher+Bloom paper against phenotypes measured with our DMS system (which we already have for cell entry in Ext. Data Fig. 1g) and doing the same for EVEscape in silico scan measurements like they have in the heatmap [here](https://evescape.org/emergingvariants) and maybe separating by spike domain? I don't think we need to add all this to paper just perhaps provide a link to such correlations might be sufficient.

**Comment by Bernadetadad** [comment]
Maybe this could also include fitness correlations to yeast DMS (basically the same we had in Cell paper Fig 7D) because in the same comment the reviewer says that in discussion "comparison [to yeast DMS] is too brief and not convincing enough".

**Comment by jbloom** [comment]
Let's discuss this in person tomorrow. I'm not sure this would address what they are asking.
