### ISSUE TITLE
A question about data 

### ISSUE THREAD

**Issue by linzhang-allan** [dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS#85]
Hello, fantastic work! 
However, when I look at the website https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/blob/main/results/summaries/per_antibody_escape.csv, I notice that some values in the escape column are negative. This confuses me, especially when I refer to your previous paper on calculating escape (paper: "Complete Mapping of Mutations to the SARS-CoV-2 Spike Receptor-Binding Domain that Escape Antibody Recognition"). Could you please explain how to normalize the escape data, including the negative values?

**Comment by linzhang-allan** [comment]
I got it! Sorry to bother you!

**Comment by jbloom** [comment]
Did you get this figured out? Basically, this repository is using a different method (pseudovirus deep mutational scanning) that measures sensitizing mutations (negative escape) that increase neutralization as well as those that escape. The "Complete Mapping of Mutations to the SARS-CoV-2 Spike Receptor-Binding Domain that Escape Antibody Recognition" was using a different yeast-display method.

**Comment by linzhang-allan** [comment]
> Did you get this figured out? Basically, this repository is using a different method (pseudovirus deep mutational scanning) that measures sensitizing mutations (negative escape) that increase neutralization as well as those that escape. The "Complete Mapping of Mutations to the SARS-CoV-2 Spike Receptor-Binding Domain that Escape Antibody Recognition" was using a different yeast-display method.

Thanks for your reply. Before your reply, I think it's a simple calculation to a standard normal distribution based on yeast-display method. I will read your paper "A pseudovirus system enables deep mutational scanning of the full SARS-CoV-2 spike" to get a further understanding of the 'pseudovirus deep mutational scanning' method.
Regards,
Allan Zhang
